config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # we map HTTP verb/url combo to a controller#action (action is a method inside the controller class)

  get("/",{to: "welcome#index", as: :root}) 
  # The route above specifies that when your application receives a `GET` request with the URL `/` Rails will handle this request by the `WelcomeController` class and `index` method within that class.
  get("/contact",{to:"contact#index"})# First we have to fetch the form
  post("/contact_submit",{to:"contact#create", as: "contact_submit"})# Then we have to decide where to send the user once form is submitted

  # ROUTES FOR QUESTIONS
  # get('/questions', to:"questions#index")
  # get('/questions/new', to: "questions#new", as: :new_question)
  # post('/questions', to: "questions#create")

  # get('/questions/:id', to: 'questions#show', as: :question)
  # # http://localhost:3000/questions/9
  # delete("/questions/:id",to: "questions#destroy")
  # get('/questions/:id/edit', to: "questions#edit", as: :edit_question)
  # patch('/questions/:id', to: "questions#update")


  # resources will built a CRUD RESTfull routes.(all of the above routes)
  # It assumes that there will be a contoller name as a first argument, pluralized and PascalCase
  # PascalCase
  resources :questions do
    resources :likes, shallow: true, only: [:create, :destroy]

    get :liked, on: :collection
    # All the resources in this block will be prefixed by this👇🏻
    # /questions/:question_id 
    # So we can now grab question_id from params like params[:question_id]

    resources :answers, only:[:create, :destroy] # this will only generate routes for :create and :destroy action
    # /questions/:question_id/answers/:id
    # /questions/:question_id/answers/:id/edit 
  end

  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  # resource is singular instead of resources
  # Unlike resources, resource will create routes that do CRUD operations only on one thing. 
  # There will be no index routes and no route will have an :id wildcard
  # Even with singular resource controller will still be plural.

  resources :job_posts, only: [:new,:create, :show, :index, :edit,:update, :destroy]
  # The namespace method in Rails routes makes it so that 
  # your app will automatically look in a directory api
  # and then in a sub directory v1 for QuestionController

  # the options 'defaults: {format: :json}' will set 'json' as the default response
  # format for all the routes contained within the block
  # /api/v1/questions
  namespace :api, defaults: {format: :json} do # we can set default response format of the block
    namespace :v1 do
      resources :questions, only:[:index, :show, :update, :create, :destroy]
      resource :session, only: [:create, :destroy]
      get('/current_user', to: 'sessions#get_current_user')
      resources :users, only:[:create]
    end
    # namespace :v2 do
    #   resources :questions
    # end
  end

end

app/views/layouts/_navbar.html.erb
<!-- NAVBAR -->
    <!-- link_to is a helper method provided by rails and   -->
    <!-- <a href='url'> LINK </a> 👈🏻 for normal html  -->
    <nav>
        <%= link_to 'Home', root_path  %>
        |
        <%= link_to 'Questions', questions_path %>
        |
        <%= link_to 'New Question', new_question_path %>
        |
        <%= link_to 'Contact Us', contact_path  %> 
        |
        <% if user_signed_in? %>
        Hello <%= current_user.full_name %> 
        |
        <%= link_to 'Liked Questions', liked_questions_path %>  
        |
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: 'Are you sure you want to log out?'}
         %>
        <% else %>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %>
        <% end %>
    </nav> 
        <!-- NAVBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswersNov2020</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <!-- Geo Codeing -->
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCKRipnVdJ9eljbFl5DbuweKV-lkmQOTGo"></script>
    <script  src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js"></script>

<script  src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'>  </script>

<script  src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'>  </script>
    
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> -->
<!-- GeoCoding -->
  </head>

  <body>
    <div class='container'>
    <%= render 'layouts/navbar'%>
    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </div>
  </body>
</html>